FROM python:3.10

 WORKDIR /app2
 COPY requirements.txt /app2/requirements.txt

 RUN pip install --no-cache-dir --upgrade -r /app2/requirements.txt

 COPY . /app2

 CMD ["uvicorn", "main:app", "--host","0.0.0.0","--port","80"]